In [5]:
import pandas as pd
import pyRAPL
import tracemalloc

In [7]:
# Load data
df = pd.read_csv('UNSW_NB15_training-set.csv')

df

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.121478,tcp,-,FIN,6,4,258,172,74.087490,...,1,1,0,0,0,1,1,0,Normal,0
1,2,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,...,1,2,0,0,0,1,6,0,Normal,0
2,3,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,...,1,3,0,0,0,2,6,0,Normal,0
3,4,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,...,1,3,1,1,0,2,1,0,Normal,0
4,5,0.449454,tcp,-,FIN,10,6,534,268,33.373826,...,1,40,0,0,0,2,39,0,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175336,175337,0.000009,udp,dns,INT,2,0,114,0,111111.107200,...,13,24,0,0,0,24,24,0,Generic,1
175337,175338,0.505762,tcp,-,FIN,10,8,620,354,33.612649,...,1,2,0,0,0,1,1,0,Shellcode,1
175338,175339,0.000009,udp,dns,INT,2,0,114,0,111111.107200,...,3,13,0,0,0,3,12,0,Generic,1
175339,175340,0.000009,udp,dns,INT,2,0,114,0,111111.107200,...,14,30,0,0,0,30,30,0,Generic,1
175340,175341,0.000009,udp,dns,INT,2,0,114,0,111111.107200,...,16,30,0,0,0,30,30,0,Generic,1

In [8]:


# Cek kolom non-numerik
non_numeric_cols = df.select_dtypes(include=['object']).columns
print("Kolom non-numerik:", non_numeric_cols)

# Encode semua kolom non-numerik menggunakan Label Encoding
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in non_numeric_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le  # simpan encoder kalau mau decode balik nanti

# Sekarang semua kolom numerik
print(df.dtypes)

Kolom non-numerik: Index(['proto', 'service', 'state', 'attack_cat'], dtype='object')
id                     int64
dur                  float64
proto                  int64
service                int64
state                  int64
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat             int64
label                  int64
dtype: object

In [19]:
import pandas as pd
import tracemalloc
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split



# Misal kolom terakhir adalah target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data (bisa juga pakai KFold kalau mau)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model
model = DecisionTreeClassifier()

# Mulai ukur memori
tracemalloc.start()

# Latih model
model.fit(X_train, y_train)

# Ambil data memori
current, peak = tracemalloc.get_traced_memory()

# Konversi ke MB
# current_MB = current / 10**6:.3f}
# peak_MB = peak / (1024 * 1024)
tracemalloc.stop()

print(f"Current Memory Usage (after training): {current / 10**6:.4f} MB")
print(f"Peak Memory Usage (during training): {peak / 10**6:.4f} MB")

Current Memory Usage (after training): 0.0059 MB
Peak Memory Usage (during training): 74.0703 MB